# Generated by Django 5.0.9 on 2026-08-31 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('aws', 'Amazon Web Services'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud')], db_index=True, max_length=10)),
                ('resource_type', models.CharField(help_text='e.g. EC2 Instance, S3 Bucket, VM, Storage Account', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='Provider-native resource identifier/ARN', max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Free-form key/value tags')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Security owner responsible for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='assets_clou_provide_df6b73_idx')],
            },
        ),
    ]
